spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: test-secret-key-for-jwt-token-generation-minimum-256-bits-required
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    com.ourtime: debug
